- hosts: remote
  tasks:
  - name: "Greeting file from Ubuntu to Centos"
    shell: |
        echo 'hello Censtos, it is Ubuntu saying Hello to you, welcome to Ansible network' > /root/fromControlNode.txt
