# Ubuntu image latest
FROM ubuntu:latest

# Disable interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Install required packages that have curl, git, and build-essential before they are used
RUN apt-get update && \
    apt-get install -y software-properties-common curl git build-essential && \
    apt-add-repository --yes --update ppa:ansible/ansible && \
    apt-get install -y openssh-server openssh-client net-tools gnupg2 ansible sshpass sudo && \
    apt-get clean

# Install Homebrew
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Add Homebrew to the PATH
ENV PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"

# Create the "nhat" user
RUN useradd -m -s /bin/bash nhat

# Set the password for the "nhat" user (change as needed)
RUN echo 'nhat:0408' | chpasswd

# Generate an SSH key for the "nhat" user
RUN mkdir -p /home/nhat/.ssh && \
    ssh-keygen -t rsa -f /home/nhat/.ssh/id_rsa -N ""

# Set correct permissions for the "nhat" home directory
RUN chown -R nhat:nhat /home/nhat

# Configure SSH to allow password and key-based authentication
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config && \
    echo 'AllowUsers nhat' >> /etc/ssh/sshd_config

# Add the "nhat" user to the sudo group
RUN usermod -aG sudo nhat

# Allow the "nhat" user to run commands with sudo without a password prompt
RUN echo "nhat ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/nhat

# Optional tool to make terminals look more pleasant
# Install oh-my-posh (as the "nhat" user)
RUN brew install jandedobbeleer/oh-my-posh/oh-my-posh 

# Add command to ~/.bashrc (for the "nhat" user)
RUN echo 'eval "$(oh-my-posh init bash --config /mytheme.json)"' >> /home/nhat/.bashrc

# Switch back to the root user
USER root

# Add 1Password CLI
RUN curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/$(dpkg --print-architecture) stable main" | tee /etc/apt/sources.list.d/1password.list

RUN mkdir -p /etc/debsig/policies/AC2D62742012EA22/ && \
    curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | tee /etc/debsig/policies/AC2D62742012EA22/1password.pol && \
    mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22 && \
    curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg

RUN apt update && apt install -y 1password-cli

# Create the privilege separation directory
RUN mkdir -p /run/sshd

# Copy the mytheme.json file from the host to the container
COPY mytheme.json /

# Copy ansible cfg file
COPY .ansible.cfg /home/nhat/

# Start SSH server as a service
CMD ["/usr/sbin/sshd", "-D"]