- hosts: ubuntu
  tasks:
    - name: load secrets
      include_vars:
        file: secrets.yml
        name: var
      no_log: false

    - name: Run a vault ls request
      shell: |
        curl -X GET http://host.docker.internal:8080/v1/vaults \
          --header 'Authorization: Bearer {{var.connect_token}}' \
          --header 'Content-type: application/json'
      register: vault_output

    - name: Write output to a file
      copy:
        content: "{{ vault_output.stdout }}"
        dest: "/var/data/connectVaultList.json"
