- hosts: ubuntu
  tasks:
    - name: Load sensitive data
      include_vars:
        file: secrets.yml
        name: var
      no_log: false  # set to true to prevent displaying sensitive data in logs

    - name: Run op commands
      shell: |
        address="{{ var.my_address }}"
        email="{{ var.my_email }}"
        secretKey="{{ var.my_secret_key }}"
        password="{{ var.my_password }}"
        eval $(echo "$password" | op account add --address $address --email $email --secret-key $secretKey --signin)
        op vault ls > ls.txt

- hosts: remote 
  tasks:
    - name: Copy ls.txt to remote hosts
      ansible.builtin.copy:
        src: /var/data/ls.txt 
        dest: /root/ls.txt 
