---
- hosts: ubuntu
  environment:
    OP_CONNECT_HOST: http://host.docker.internal:8080
  collections:
    - onepassword.connect
  tasks:
    - name: Load connect_token from secrets file
      include_vars:
        file: secrets.yml
        name: connect_token
    - name: Find the item
      item_info:
        token: "{{ connect_token.connect_token }}"
        item: zy362ecgocf7et4n422r27mkzm
        vault: vznh73vmml3xake4byghvbydda
      no_log: false
      register: op_item
